/* NexusCRM v4 — app.js — Universal All-in-One CRM */
const TOKEN=localStorage.getItem('nexus_token');
const CUSER=JSON.parse(localStorage.getItem('nexus_user')||'{}');
const TENANT=JSON.parse(localStorage.getItem('nexus_tenant')||'{}');
if(!TOKEN)window.location.href='/login.html';
const H=()=>({'Content-Type':'application/json','Authorization':`Bearer ${TOKEN}`});
async function api(path,opts={}){try{const res=await fetch(path,{headers:H(),...opts});if(res.status===401||res.status===403){logout();return null;}return res;}catch{toast('Server unreachable','error');return null;}}

// State
let contacts=[],invoices=[],messages=[],templates=[],reminders=[],proposals=[];
let projects=[],tickets=[],contracts=[],expenses=[],campaigns=[],flows=[];
let dragId=null,activeMsgCid=null,activeChannel='whatsapp',editingId=null,isAdding=false;
let invItems=[],propItems=[],aiHistory=[];

// Helpers
const PALS=[{bg:'rgba(59,130,246,.2)',c:'#60a5fa'},{bg:'rgba(34,197,94,.18)',c:'#4ade80'},{bg:'rgba(245,158,11,.18)',c:'#fbbf24'},{bg:'rgba(168,85,247,.18)',c:'#c084fc'},{bg:'rgba(20,184,166,.18)',c:'#2dd4bf'},{bg:'rgba(249,115,22,.18)',c:'#fb923c'}];
const pal=n=>{let h=0;for(const c of(n||''))h=(h*31+c.charCodeAt(0))&0xffff;return PALS[h%PALS.length]};
const init=n=>(n||'?').split(' ').map(p=>p[0]).join('').slice(0,2).toUpperCase();
const setAv=(el,n)=>{const p=pal(n);el.style.background=p.bg;el.style.color=p.c;el.textContent=init(n)};
const $m=v=>v!=null?'$'+Number(v).toLocaleString('en-US',{minimumFractionDigits:0,maximumFractionDigits:0}):'—';
const $d=d=>d?new Date(d).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'—';
const $ago=d=>{if(!d)return'—';const s=Math.floor((Date.now()-new Date(d))/1000);if(s<60)return'just now';if(s<3600)return`${Math.floor(s/60)}m ago`;if(s<86400)return`${Math.floor(s/3600)}h ago`;return`${Math.floor(s/86400)}d ago`};
const scoreColor=s=>s>=70?'var(--accent-green)':s>=40?'var(--accent-amber)':'var(--accent-red)';

function toast(msg,type='success'){const d=document.createElement('div');d.className=`toast ${type}`;d.innerHTML=`<span class="toast-dot"></span>${msg}`;document.getElementById('toastContainer').appendChild(d);setTimeout(()=>d.remove(),3500)}

// Clock
setInterval(()=>{const el=document.getElementById('topbarTime');if(el)el.textContent=new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',second:'2-digit'})},1000);

// Theme
let dark=true;
document.getElementById('themeToggle')?.addEventListener('click',()=>{dark=!dark;document.body.classList.toggle('light',!dark)});

// Sidebar
function initSidebar(){
  const name=CUSER.name||'User',role=CUSER.role||'user',plan=TENANT.plan||'starter';
  document.getElementById('sidebarName').textContent=name;
  document.getElementById('sidebarRole').textContent=role.charAt(0).toUpperCase()+role.slice(1);
  setAv(document.getElementById('sidebarAvatar'),name);
  const chip=document.getElementById('planChip');chip.textContent=plan;chip.className=`plan-chip ${plan}`;
  if(role==='admin')document.querySelectorAll('.admin-only').forEach(el=>el.style.display='flex');
}

function logout(){localStorage.clear();window.location.href='/login.html'}
document.getElementById('logoutBtn')?.addEventListener('click',logout);
document.getElementById('menuToggle')?.addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('open'));

// Navigation
const TITLES={dashboard:'Dashboard',ai:'AI Assistant',contacts:'Contacts',pipeline:'Pipeline',messaging:'Messaging',proposals:'Proposals',invoices:'Invoices',contracts:'Contracts',projects:'Projects',helpdesk:'Help Desk',finance:'Finance',campaigns:'Campaigns',automation:'Automation',templates:'Templates',reminders:'Reminders',analytics:'Analytics',team:'Team',billing:'Billing',admin:'Admin'};
document.querySelectorAll('[data-page]').forEach(el=>{el.addEventListener('click',e=>{e.preventDefault();navigateTo(el.dataset.page);document.getElementById('sidebar').classList.remove('open')})});

function navigateTo(page){
  document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));
  document.querySelectorAll('.nav-item').forEach(n=>n.classList.remove('active'));
  document.getElementById(`page-${page}`)?.classList.add('active');
  document.querySelectorAll(`[data-page="${page}"]`).forEach(el=>el.classList.add('active'));
  document.getElementById('pageTitle').textContent=TITLES[page]||page;
  const renders={dashboard:renderDashboard,ai:renderAI,contacts:renderContacts,pipeline:renderPipeline,messaging:renderMessaging,proposals:renderProposals,invoices:renderInvoices,contracts:renderContracts,projects:renderProjects,helpdesk:renderHelpDesk,finance:renderFinance,campaigns:renderCampaigns,automation:renderAutomation,templates:renderTemplates,reminders:renderReminders,analytics:renderAnalytics,team:renderTeam,billing:renderBilling,admin:renderAdmin};
  if(renders[page])renders[page]();
}

// Load all
async function loadAll(){
  const rs=await Promise.all([api('/api/contacts'),api('/api/invoices'),api('/api/messages'),api('/api/templates'),api('/api/reminders'),api('/api/proposals'),api('/api/projects'),api('/api/tickets'),api('/api/contracts'),api('/api/expenses'),api('/api/campaigns'),api('/api/automation')]);
  if(rs[0])contacts=await rs[0].json();
  if(rs[1])invoices=await rs[1].json();
  if(rs[2])messages=await rs[2].json();
  if(rs[3])templates=await rs[3].json();
  if(rs[4])reminders=await rs[4].json();
  if(rs[5])proposals=await rs[5].json();
  if(rs[6])projects=await rs[6].json();
  if(rs[7])tickets=await rs[7].json();
  if(rs[8])contracts=await rs[8].json();
  if(rs[9])expenses=await rs[9].json();
  if(rs[10])campaigns=await rs[10].json();
  if(rs[11])flows=await rs[11].json();
  document.getElementById('navContactCount').textContent=contacts.length;
  const pendR=reminders.filter(r=>r.status==='pending'&&new Date(r.due_at)<=new Date(Date.now()+86400000)).length;
  if(document.getElementById('navRemCount'))document.getElementById('navRemCount').textContent=pendR||'';
  if(document.getElementById('navTicketCount'))document.getElementById('navTicketCount').textContent=tickets.filter(t=>t.status==='open').length||'';
  if(document.getElementById('navPropCount'))document.getElementById('navPropCount').textContent=proposals.filter(p=>p.status==='sent').length||'';
}

// DASHBOARD
async function renderDashboard(){
  const res=await api('/api/stats');if(!res)return;
  const d=await res.json();
  const hr=new Date().getHours();
  document.getElementById('dashGreeting').textContent=`${hr<12?'Good morning':hr<17?'Good afternoon':'Good evening'}, ${CUSER.name?.split(' ')[0]||''}`;
  animCount('kpiContacts',d.total_contacts);
  document.getElementById('kpiRevenue').textContent=$m(d.revenue);
  document.getElementById('kpiPipeline').textContent=$m(d.pipeline);
  animCount('kpiTickets',d.open_tickets||0);
  animCount('kpiProjects',d.active_projects||0);
  animCount('kpiContracts',d.active_contracts||0);
  document.getElementById('kpiExpenses').textContent=$m(d.total_expenses||0);
  animCount('kpiReminders',d.pending_reminders||0);
  document.getElementById('kpiLeadsDelta').textContent=`${d.leads} leads · ${d.clients} clients`;
  document.getElementById('recentContacts').innerHTML=contacts.slice(0,5).map(c=>{const p=pal(c.name);return`<div class="recent-item" onclick="openView(${c.id})"><div class="r-avatar" style="background:${p.bg};color:${p.c}">${init(c.name)}</div><div><div class="r-name">${c.name}</div><div class="r-meta">${c.company||'—'}</div></div><span class="status-badge badge-${c.status}">${c.status}</span></div>`}).join('')||'<div style="padding:20px;color:var(--text-muted);font-size:13px">No contacts yet</div>';
  const total=contacts.length||1;
  document.getElementById('statusChart').innerHTML=['Lead','Client','Partner','Churned'].map(s=>{const cols={Lead:'var(--accent-amber)',Client:'var(--accent-green)',Partner:'var(--accent-blue)',Churned:'var(--accent-red)'};const n=contacts.filter(c=>c.status===s).length;return`<div class="status-row"><div class="sr-header"><span class="sr-label">${s}</span><span class="sr-count">${n}</span></div><div class="bar-track"><div class="bar-fill" style="width:${Math.round(n/total*100)}%;background:${cols[s]}"></div></div></div>`}).join('');
  document.getElementById('activityFeed').innerHTML=(d.recent_activity||[]).slice(0,10).map(a=>`<div class="activity-item"><div class="ai-dot"></div><div class="ai-text"><b>${a.user_name||'System'}</b> ${a.action.replace(/_/g,' ')}${a.contact_name?` · ${a.contact_name}`:''}</div><div class="ai-time">${$ago(a.created_at)}</div></div>`).join('')||'<div style="padding:20px;color:var(--text-muted);font-size:13px">No activity yet</div>';
  const br=await api('/api/ai/briefing');if(!br)return;
  const bd=await br.json();
  const briefEl=document.getElementById('aiBriefing');
  if(briefEl)briefEl.innerHTML=bd.high_priority?.length?bd.high_priority.map(s=>{const p=pal(s.name);return`<div class="recent-item" onclick="navigateTo('contacts')" style="cursor:pointer"><div class="r-avatar" style="background:${p.bg};color:${p.c}">${init(s.name)}</div><div style="flex:1"><div class="r-name">${s.name} <span style="font-size:11px;font-weight:400;color:var(--text-secondary)">· Score: <span style="color:${scoreColor(s.score)}">${s.score}%</span></span></div><div class="r-meta">${s.reason}</div></div><div style="font-size:11px;color:var(--accent-amber);flex-shrink:0">${s.action}</div></div>`}).join(''):'<div style="padding:14px 18px;font-size:13px;color:var(--text-muted)">✅ All contacts are up to date.</div>';
}

function animCount(id,target){const el=document.getElementById(id);if(!el)return;let cur=0;const step=Math.max(1,Math.ceil(target/30));const t=setInterval(()=>{cur=Math.min(cur+step,target);el.textContent=cur;if(cur>=target)clearInterval(t)},25)}

// AI ASSISTANT
function renderAI(){}

document.getElementById('aiSend')?.addEventListener('click',sendAIMessage);
document.getElementById('aiInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendAIMessage()}});
document.getElementById('clearAiBtn')?.addEventListener('click',async()=>{await api('/api/ai/chat',{method:'DELETE'});aiHistory=[];document.getElementById('aiThread').innerHTML='<div class="ai-msg assistant"><div class="ai-msg-av">🤖</div><div class="ai-msg-content">Chat cleared! How can I help you?</div></div>';});

async function sendAIMessage(){
  const input=document.getElementById('aiInput');
  const text=input?.value?.trim();if(!text)return;
  input.value='';
  const thread=document.getElementById('aiThread');
  thread.innerHTML+=`<div class="ai-msg user"><div class="ai-msg-av">👤</div><div class="ai-msg-content">${text}</div></div>`;
  const typing=document.createElement('div');typing.className='ai-msg assistant';typing.innerHTML='<div class="ai-msg-av">🤖</div><div class="ai-typing"><span></span><span></span><span></span></div>';
  thread.appendChild(typing);thread.scrollTop=thread.scrollHeight;
  const res=await api('/api/ai/chat',{method:'POST',body:JSON.stringify({message:text})});
  typing.remove();
  if(res){const d=await res.json();thread.innerHTML+=`<div class="ai-msg assistant"><div class="ai-msg-av">🤖</div><div class="ai-msg-content">${(d.reply||'').replace(/\n/g,'<br>')}</div></div>`;}
  thread.scrollTop=thread.scrollHeight;
}

// CONTACTS
function renderContacts(){
  const q=(document.getElementById('searchInput')?.value||'').toLowerCase();
  const st=document.getElementById('filterStatus')?.value||'';
  const filtered=contacts.filter(c=>{const mq=!q||c.name.toLowerCase().includes(q)||(c.email||'').toLowerCase().includes(q)||(c.company||'').toLowerCase().includes(q);return mq&&(!st||c.status===st)});
  const body=document.getElementById('tableBody');
  document.getElementById('emptyState').style.display=filtered.length?'none':'block';
  body.innerHTML='';
  filtered.forEach(c=>{const p=pal(c.name);const score=c.deal_score??0;const tr=document.createElement('tr');
    tr.innerHTML=`<td onclick="openView(${c.id})"><div class="contact-cell"><div class="t-avatar" style="background:${p.bg};color:${p.c}">${init(c.name)}</div><div><div class="t-name">${c.name}</div><div class="t-email">${c.email||'—'}</div></div></div></td><td onclick="openView(${c.id})"><div style="font-weight:500">${c.company||'—'}</div><div style="font-size:11px;color:var(--text-secondary)">${c.title||'—'}</div></td><td onclick="openView(${c.id})"><span class="status-badge badge-${c.status}">${c.status}</span></td><td onclick="openView(${c.id})" style="font-weight:500">${$m(c.deal)}</td><td onclick="openView(${c.id})"><div style="display:flex;align-items:center;gap:5px"><div style="flex:1;height:4px;background:var(--bg-elevated);border-radius:99px;overflow:hidden"><div style="width:${score}%;height:100%;background:${scoreColor(score)};border-radius:99px"></div></div><span style="font-size:11px;color:${scoreColor(score)};font-weight:500;width:28px;text-align:right">${score}%</span></div></td><td><div class="actions-cell"><button class="icon-btn" title="WhatsApp" onclick="quickWA(${c.id})" style="color:#25d366"><svg viewBox="0 0 20 20" fill="currentColor" width="11" height="11"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347zM10 0C4.477 0 0 4.477 0 10c0 1.89.525 3.656 1.438 5.168L0 20l4.948-1.42A9.956 9.956 0 0010 20c5.523 0 10-4.477 10-10S15.523 0 10 0z"/></svg></button><button class="icon-btn" title="Edit" onclick="openEdit(${c.id})"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M11 2l3 3-8 8H3v-3l8-8z"/></svg></button><button class="icon-btn del" title="Delete" onclick="handleDelete(${c.id})"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M2 4h12M5 4V2h6v2M6 7v5M10 7v5M3 4l1 10h8l1-10"/></svg></button></div></td>`;
    body.appendChild(tr);});
}
document.getElementById('searchInput')?.addEventListener('input',renderContacts);
document.getElementById('filterStatus')?.addEventListener('change',renderContacts);
document.getElementById('addContactBtn')?.addEventListener('click',openAdd);
document.getElementById('exportBtn')?.addEventListener('click',exportCSV);

// PIPELINE
const STAGES=['Lead','Qualified','Proposal','Closed'];
const SCOLS={Lead:'#f59e0b',Qualified:'#3b82f6',Proposal:'#a855f7',Closed:'#22c55e'};
function renderPipeline(){
  const board=document.getElementById('kanbanBoard');board.innerHTML='';
  STAGES.forEach(stage=>{
    const cards=contacts.filter(c=>(c.stage||c.status)===stage);
    const value=cards.reduce((s,c)=>s+(Number(c.deal)||0),0);
    const col=document.createElement('div');col.className='kanban-col';col.dataset.stage=stage;
    col.innerHTML=`<div class="kanban-col-header"><span class="kanban-dot" style="background:${SCOLS[stage]}"></span><span class="kanban-col-name">${stage}</span><span class="kanban-col-count">${cards.length}</span><span class="kanban-col-value">${$m(value)}</span></div><div class="kanban-cards" id="kcol-${stage}"></div>`;
    board.appendChild(col);
    const zone=col.querySelector('.kanban-cards');
    cards.forEach(c=>{const card=document.createElement('div');card.className='kanban-card';card.draggable=true;card.dataset.id=c.id;const p=pal(c.name);const score=c.deal_score??0;card.innerHTML=`<div style="display:flex;align-items:center;gap:6px;margin-bottom:3px"><div style="width:20px;height:20px;border-radius:50%;background:${p.bg};color:${p.c};font-size:8px;font-weight:600;display:flex;align-items:center;justify-content:center">${init(c.name)}</div><div class="kc-name">${c.name}</div></div><div class="kc-company">${c.company||'—'}</div><div style="display:flex;justify-content:space-between;align-items:center"><div class="kc-value">${$m(c.deal)}</div><div style="font-size:10px;color:${scoreColor(score)}">${score}%</div></div>`;
      card.addEventListener('dragstart',()=>{dragId=c.id;setTimeout(()=>card.classList.add('dragging'),0)});
      card.addEventListener('dragend',()=>{card.classList.remove('dragging');dragId=null});
      card.addEventListener('click',()=>openView(c.id));zone.appendChild(card);});
    zone.addEventListener('dragover',e=>{e.preventDefault();col.classList.add('drag-over')});
    zone.addEventListener('dragleave',()=>col.classList.remove('drag-over'));
    zone.addEventListener('drop',async e=>{e.preventDefault();col.classList.remove('drag-over');if(!dragId)return;const contact=contacts.find(c=>c.id===dragId);if(!contact||(contact.stage||contact.status)===stage)return;const res=await api(`/api/contacts/${dragId}/stage`,{method:'PATCH',body:JSON.stringify({stage})});if(res?.ok){contact.stage=stage;renderPipeline();toast(`Moved ${contact.name} → ${stage}`)}});
  });
}

// MESSAGING
function renderMessaging(){renderMsgList()}
function renderMsgList(filter=''){
  const q=filter.toLowerCase();
  const filtered=contacts.filter(c=>!q||c.name.toLowerCase().includes(q)||(c.company||'').toLowerCase().includes(q));
  document.getElementById('msgContactList').innerHTML=filtered.map(c=>{const p=pal(c.name);const lastMsg=messages.find(m=>m.contact_id===c.id);return`<div class="msg-contact-item ${activeMsgCid===c.id?'active':''}" onclick="openMsgContact(${c.id})"><div class="mci-avatar" style="background:${p.bg};color:${p.c}">${init(c.name)}</div><div style="flex:1;overflow:hidden"><div class="mci-name">${c.name}</div><div class="mci-preview">${lastMsg?lastMsg.content.slice(0,38):c.company||'No messages'}</div></div><div class="mci-time">${lastMsg?$ago(lastMsg.sent_at):''}</div></div>`}).join('');
}
document.getElementById('msgSearch')?.addEventListener('input',e=>renderMsgList(e.target.value));
async function openMsgContact(id){
  activeMsgCid=id;renderMsgList(document.getElementById('msgSearch').value);
  const contact=contacts.find(c=>c.id===id);if(!contact)return;
  document.getElementById('msgEmpty').style.display='none';
  const chat=document.getElementById('msgChat');chat.style.display='flex';
  const p=pal(contact.name);
  document.getElementById('msgHeader').innerHTML=`<div class="msg-h-avatar" style="background:${p.bg};color:${p.c}">${init(contact.name)}</div><div><div class="msg-h-name">${contact.name}</div><div class="msg-h-meta">${contact.company||'—'} · ${contact.phone||'No phone'}</div></div><div class="msg-h-actions"><button class="ch-btn wa-btn ${activeChannel==='whatsapp'?'active':''}" onclick="setChannel('whatsapp')">WhatsApp</button><button class="ch-btn ${activeChannel==='email'?'active':''}" onclick="setChannel('email')">Email</button><button class="ch-btn sms-btn ${activeChannel==='sms'?'active':''}" onclick="setChannel('sms')">SMS</button><button class="ch-btn note-btn ${activeChannel==='note'?'active':''}" onclick="setChannel('note')">Note</button></div>`;
  await loadThread(id);renderCompose(contact);
}
async function loadThread(id){
  const res=await api(`/api/contacts/${id}/messages`);if(!res)return;
  const msgs=await res.json();
  const thread=document.getElementById('msgThread');
  thread.innerHTML=msgs.map(m=>{const out=m.direction==='outbound';return`<div class="msg-bubble ${out?'out':'in'}"><div class="bubble-inner">${m.content}</div><div class="bubble-meta"><span class="ch-pip ${m.channel}">${m.channel}</span>${$ago(m.sent_at)}</div></div>`}).join('')||'<div style="padding:24px;color:var(--text-muted);font-size:13px;text-align:center">No messages yet</div>';
  thread.scrollTop=thread.scrollHeight;
}
function setChannel(ch){activeChannel=ch;if(activeMsgCid)openMsgContact(activeMsgCid)}
function renderCompose(contact){
  const isEmail=activeChannel==='email';
  document.getElementById('msgCompose').innerHTML=`${isEmail?`<div style="margin-bottom:6px"><input type="text" id="emailSubject" class="fi" placeholder="Email subject…"/></div>`:''}<div class="compose-row"><select id="templatePicker" class="fi" style="width:auto;padding:7px 9px;font-size:12px" onchange="applyTpl(${contact.id})"><option value="">Template…</option>${templates.filter(t=>t.channel===activeChannel).map(t=>`<option value="${t.id}">${t.name}</option>`).join('')}</select><textarea class="compose-ta" id="composeText" placeholder="${activeMsgCid?getPH():''}" rows="2"></textarea><button class="send-btn" onclick="sendMsg(${contact.id})"><svg viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.5"><line x1="3" y1="10" x2="17" y2="10"/><polyline points="12,5 17,10 12,15"/></svg></button></div><div class="compose-hint">${getHint(contact)}</div>`;
  document.getElementById('composeText').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMsg(contact.id)}});
}
function getPH(){return activeChannel==='whatsapp'?'Type a WhatsApp message…':activeChannel==='email'?'Email body…':activeChannel==='sms'?'SMS…':'Add a note…'}
function getHint(c){if(activeChannel==='whatsapp')return c.whatsapp||c.phone?`Opens WhatsApp to <b>${c.whatsapp||c.phone}</b>`:'⚠ No WhatsApp number';if(activeChannel==='email')return c.email?`To: <b>${c.email}</b>`:'⚠ No email';if(activeChannel==='sms')return c.phone?`SMS to <b>${c.phone}</b>`:'⚠ No phone';return'Note saved to contact log'}
async function applyTpl(cid){const tid=parseInt(document.getElementById('templatePicker').value);if(!tid)return;const res=await api(`/api/templates/${tid}/preview`,{method:'POST',body:JSON.stringify({contact_id:cid})});if(!res)return;const d=await res.json();document.getElementById('composeText').value=d.body;const sub=document.getElementById('emailSubject');if(sub&&d.subject)sub.value=d.subject;}
async function sendMsg(contactId){
  const text=document.getElementById('composeText')?.value?.trim();if(!text)return;
  const contact=contacts.find(c=>c.id===contactId);if(!contact)return;
  if(activeChannel==='whatsapp'){const res=await api(`/api/contacts/${contactId}/whatsapp`,{method:'POST',body:JSON.stringify({message:text})});if(!res)return;const data=await res.json();if(data.waUrl){window.open(data.waUrl,'_blank');toast('WhatsApp opened · logged')}else toast(data.warning||data.error,'warn');}
  else if(activeChannel==='email'){const subject=document.getElementById('emailSubject')?.value?.trim();if(!subject){toast('Subject required','warn');return}const res=await api(`/api/contacts/${contactId}/email`,{method:'POST',body:JSON.stringify({subject,body:text})});if(!res)return;const data=await res.json();toast(data.message||data.warning,data.warning?'warn':'success');}
  else if(activeChannel==='sms'){const res=await api(`/api/contacts/${contactId}/sms`,{method:'POST',body:JSON.stringify({message:text})});if(!res)return;const data=await res.json();toast(data.message||data.warning,data.warning?'warn':'success');}
  else{await api(`/api/contacts/${contactId}/messages`,{method:'POST',body:JSON.stringify({channel:'note',content:text})});toast('Note saved');}
  document.getElementById('composeText').value='';
  await loadThread(contactId);await loadAll();renderMsgList(document.getElementById('msgSearch').value);
}
async function quickWA(id){
  const contact=contacts.find(c=>c.id===id);if(!contact)return;
  openModal(`WhatsApp — ${contact.name}`,`<div class="form-group"><label>Message</label><textarea class="fi ta" id="qaMsg" rows="3" placeholder="Type message…"></textarea></div>`,[{label:'Open WhatsApp',cls:'btn-primary',action:async()=>{const text=document.getElementById('qaMsg').value.trim();if(!text)return;const res=await api(`/api/contacts/${id}/whatsapp`,{method:'POST',body:JSON.stringify({message:text})});const data=await res.json();if(data.waUrl){window.open(data.waUrl,'_blank');toast('WhatsApp opened');closeModal();await loadAll()}else toast(data.warning||data.error,'warn');}}]);
}

// PROPOSALS
function renderProposals(){
  document.getElementById('proposalBody').innerHTML=proposals.map(p=>`<tr><td style="font-weight:500">${p.proposal_number}</td><td>${p.title}</td><td>${p.contact_name||'—'}<div style="font-size:11px;color:var(--text-secondary)">${p.company||''}</div></td><td><span class="status-badge prop-${p.status}">${p.status}</span></td><td style="font-weight:500">${$m(p.total)} ${p.currency||'USD'}</td><td style="color:var(--text-secondary)">${$d(p.valid_until)}</td><td><div class="actions-cell">${p.status==='draft'?`<button class="icon-btn" title="Send" onclick="sendProposal(${p.id})"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><line x1="3" y1="8" x2="13" y2="8"/><polyline points="9,4 13,8 9,12"/></svg></button>`:''} ${p.status==='sent'?`<button class="icon-btn" title="Mark Accepted" onclick="proposalStatus(${p.id},'accepted')"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><polyline points="2,8 6,12 14,4"/></svg></button>`:''}<button class="icon-btn del" onclick="deleteProposal(${p.id})"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M2 4h12M5 4V2h6v2M6 7v5M10 7v5M3 4l1 10h8l1-10"/></svg></button></div></td></tr>`).join('')||'<tr><td colspan="7" style="padding:40px;text-align:center;color:var(--text-muted)">No proposals yet</td></tr>';
}
document.getElementById('addProposalBtn')?.addEventListener('click',()=>{propItems=[];const cOpts=contacts.map(c=>`<option value="${c.id}">${c.name} — ${c.company||'—'}</option>`).join('');openModal('New Proposal',`<div class="form-group"><label>Contact</label><select class="fi" id="prop-contact"><option value="">Select…</option>${cOpts}</select></div><div class="form-group"><label>Title</label><input class="fi" id="prop-title" placeholder="Proposal title"/></div><div class="form-group"><label>Intro</label><textarea class="fi ta" id="prop-intro" rows="2" placeholder="Introduction text…"></textarea></div><div class="form-group"><label>Line Items</label><div id="propItemsList"></div><button class="btn-ghost" style="margin-top:6px;font-size:12px" onclick="addPropItem()">+ Add Item</button></div><div class="form-group"><label>Discount ($)</label><input type="number" class="fi" id="prop-discount" value="0"/></div><div class="form-group"><label>Valid Until</label><input type="date" class="fi" id="prop-valid"/></div><div class="form-group"><label>Currency</label><select class="fi" id="prop-currency"><option>USD</option><option>EUR</option><option>GBP</option><option>KES</option></select></div>`,[{label:'Create',cls:'btn-primary',action:saveProposal}]);addPropItem();});
function addPropItem(){propItems.push({description:'',quantity:1,unit_price:0});const idx=propItems.length-1;const row=document.createElement('div');row.style.cssText='display:grid;grid-template-columns:1fr 55px 85px 26px;gap:5px;margin-bottom:5px';row.innerHTML=`<input class="fi" placeholder="Description" oninput="propItems[${idx}].description=this.value"/><input class="fi" type="number" value="1" min="1" oninput="propItems[${idx}].quantity=+this.value"/><input class="fi" type="number" value="0" oninput="propItems[${idx}].unit_price=+this.value"/><button class="icon-btn del" onclick="this.parentElement.remove();propItems.splice(${idx},1)"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><line x1="3" y1="3" x2="13" y2="13"/><line x1="13" y1="3" x2="3" y2="13"/></svg></button>`;document.getElementById('propItemsList').appendChild(row);}
async function saveProposal(){const data={contact_id:parseInt(document.getElementById('prop-contact').value)||null,title:document.getElementById('prop-title').value.trim(),intro:document.getElementById('prop-intro').value.trim(),valid_until:document.getElementById('prop-valid').value,currency:document.getElementById('prop-currency').value,discount:parseFloat(document.getElementById('prop-discount').value)||0,items:propItems.filter(i=>i.description)};if(!data.title||!data.items.length){toast('Title and items required','warn');return}const res=await api('/api/proposals',{method:'POST',body:JSON.stringify(data)});if(!res?.ok){toast('Failed','error');return}toast('Proposal created!');propItems=[];closeModal();const pr=await api('/api/proposals');if(pr)proposals=await pr.json();renderProposals();}
async function sendProposal(id){const res=await api(`/api/proposals/${id}/send`,{method:'POST'});if(!res)return;const d=await res.json();toast(d.message||d.warning,d.warning?'warn':'success');const pr=await api('/api/proposals');if(pr)proposals=await pr.json();renderProposals();}
async function proposalStatus(id,status){await api(`/api/proposals/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});toast(`Proposal ${status}!`);const pr=await api('/api/proposals');if(pr)proposals=await pr.json();renderProposals();}
async function deleteProposal(id){if(!confirm('Delete?'))return;await api(`/api/proposals/${id}`,{method:'DELETE'});toast('Deleted');const pr=await api('/api/proposals');if(pr)proposals=await pr.json();renderProposals();}

// INVOICES
function renderInvoices(){
  const q=(document.getElementById('invSearch')?.value||'').toLowerCase();const st=document.getElementById('invFilterStatus')?.value||'';
  const filtered=invoices.filter(i=>{const mq=!q||(i.invoice_number||'').toLowerCase().includes(q)||(i.contact_name||'').toLowerCase().includes(q);return mq&&(!st||i.status===st)});
  document.getElementById('invoiceBody').innerHTML=filtered.map(i=>`<tr><td style="font-weight:500">${i.invoice_number}</td><td>${i.contact_name||'—'}<div style="font-size:11px;color:var(--text-secondary)">${i.company||''}</div></td><td><span class="status-badge inv-status-${i.status}">${i.status}</span></td><td style="font-weight:500">${$m(i.total)}</td><td style="color:var(--text-secondary)">${$d(i.due_date)}</td><td><div class="actions-cell">${i.status==='draft'?`<button class="icon-btn" title="Send" onclick="sendInvoice(${i.id})"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><line x1="3" y1="8" x2="13" y2="8"/><polyline points="9,4 13,8 9,12"/></svg></button>`:''} ${i.status==='sent'?`<button class="icon-btn" title="Mark Paid" onclick="markPaid(${i.id})"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><polyline points="2,8 6,12 14,4"/></svg></button>`:''}<button class="icon-btn del" onclick="deleteInvoice(${i.id})"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M2 4h12M5 4V2h6v2M6 7v5M10 7v5M3 4l1 10h8l1-10"/></svg></button></div></td></tr>`).join('')||'<tr><td colspan="6" style="padding:40px;text-align:center;color:var(--text-muted)">No invoices yet</td></tr>';
}
document.getElementById('invSearch')?.addEventListener('input',renderInvoices);
document.getElementById('invFilterStatus')?.addEventListener('change',renderInvoices);
document.getElementById('addInvoiceBtn')?.addEventListener('click',()=>{invItems=[];const cOpts=contacts.map(c=>`<option value="${c.id}">${c.name} — ${c.company||'—'}</option>`).join('');openModal('New Invoice',`<div class="form-group"><label>Contact</label><select class="fi" id="inv-contact"><option value="">Select…</option>${cOpts}</select></div><div class="form-group"><label>Currency</label><select class="fi" id="inv-currency"><option>USD</option><option>EUR</option><option>GBP</option><option>KES</option></select></div><div class="form-group"><label>Due Date</label><input type="date" class="fi" id="inv-due"/></div><div class="form-group"><label>Tax Rate (%)</label><input type="number" class="fi" id="inv-tax" value="0"/></div><div class="form-group"><label>Line Items</label><div id="invItemsList"></div><button class="btn-ghost" style="margin-top:6px;font-size:12px" onclick="addInvItem()">+ Add Item</button></div>`,[{label:'Create Invoice',cls:'btn-primary',action:saveInvoice}]);addInvItem();});
function addInvItem(){invItems.push({description:'',quantity:1,unit_price:0});const idx=invItems.length-1;const row=document.createElement('div');row.style.cssText='display:grid;grid-template-columns:1fr 55px 85px 26px;gap:5px;margin-bottom:5px';row.innerHTML=`<input class="fi" placeholder="Description" oninput="invItems[${idx}].description=this.value"/><input class="fi" type="number" value="1" min="1" oninput="invItems[${idx}].quantity=+this.value"/><input class="fi" type="number" value="0" oninput="invItems[${idx}].unit_price=+this.value"/><button class="icon-btn del" onclick="this.parentElement.remove();invItems.splice(${idx},1)"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><line x1="3" y1="3" x2="13" y2="13"/><line x1="13" y1="3" x2="3" y2="13"/></svg></button>`;document.getElementById('invItemsList').appendChild(row);}
async function saveInvoice(){const data={contact_id:parseInt(document.getElementById('inv-contact').value)||null,currency:document.getElementById('inv-currency').value,tax_rate:parseFloat(document.getElementById('inv-tax').value)||0,due_date:document.getElementById('inv-due').value,items:invItems.filter(i=>i.description)};if(!data.items.length){toast('Add items','warn');return}const res=await api('/api/invoices',{method:'POST',body:JSON.stringify(data)});if(!res?.ok){toast('Failed','error');return}toast('Invoice created!');invItems=[];closeModal();const ir=await api('/api/invoices');if(ir)invoices=await ir.json();renderInvoices();}
async function sendInvoice(id){const res=await api(`/api/invoices/${id}/send`,{method:'POST'});if(!res)return;const d=await res.json();toast(d.message||d.warning,d.warning?'warn':'success');const ir=await api('/api/invoices');if(ir)invoices=await ir.json();renderInvoices();}
async function markPaid(id){await api(`/api/invoices/${id}/status`,{method:'PATCH',body:JSON.stringify({status:'paid'})});toast('Marked paid 💰');const ir=await api('/api/invoices');if(ir)invoices=await ir.json();renderInvoices();}
async function deleteInvoice(id){if(!confirm('Delete invoice?'))return;await api(`/api/invoices/${id}`,{method:'DELETE'});toast('Deleted');const ir=await api('/api/invoices');if(ir)invoices=await ir.json();renderInvoices();}

// CONTRACTS
function renderContracts(){
  document.getElementById('contractBody').innerHTML=contracts.map(c=>`<tr><td style="font-weight:500">${c.contract_number}</td><td>${c.title}</td><td>${c.contact_name||'—'}<div style="font-size:11px;color:var(--text-secondary)">${c.company||''}</div></td><td><span class="status-badge ctr-${c.status}">${c.status}</span></td><td style="font-weight:500">${$m(c.value)}</td><td style="color:var(--text-secondary)">${$d(c.end_date)}</td><td><div class="actions-cell">${c.status==='draft'?`<button class="icon-btn" title="Mark Signed" onclick="signContract(${c.id})"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><polyline points="2,8 6,12 14,4"/></svg></button>`:''}<button class="icon-btn del" onclick="deleteContract(${c.id})"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M2 4h12M5 4V2h6v2M6 7v5M10 7v5M3 4l1 10h8l1-10"/></svg></button></div></td></tr>`).join('')||'<tr><td colspan="7" style="padding:40px;text-align:center;color:var(--text-muted)">No contracts yet</td></tr>';
}
document.getElementById('addContractBtn')?.addEventListener('click',()=>{const cOpts=contacts.map(c=>`<option value="${c.id}">${c.name} — ${c.company||'—'}</option>`).join('');openModal('New Contract',`<div class="form-group"><label>Contact</label><select class="fi" id="ctr-contact"><option value="">Select…</option>${cOpts}</select></div><div class="form-group"><label>Title</label><input class="fi" id="ctr-title" placeholder="Contract title"/></div><div class="form-group"><label>Value ($)</label><input type="number" class="fi" id="ctr-value" value="0"/></div><div class="form-group"><label>Start Date</label><input type="date" class="fi" id="ctr-start"/></div><div class="form-group"><label>End Date</label><input type="date" class="fi" id="ctr-end"/></div><div class="form-group"><label>Auto Renew</label><select class="fi" id="ctr-renew"><option value="false">No</option><option value="true">Yes</option></select></div><div class="form-group"><label>Notes</label><textarea class="fi ta" id="ctr-notes" rows="2"></textarea></div>`,[{label:'Create',cls:'btn-primary',action:async()=>{const data={title:document.getElementById('ctr-title').value.trim(),value:parseFloat(document.getElementById('ctr-value').value)||0,start_date:document.getElementById('ctr-start').value,end_date:document.getElementById('ctr-end').value,auto_renew:document.getElementById('ctr-renew').value==='true',notes:document.getElementById('ctr-notes').value,status:'draft'};const cid=parseInt(document.getElementById('ctr-contact').value)||null;if(!data.title){toast('Title required','warn');return}await api('/api/contracts',{method:'POST',body:JSON.stringify({contact_id:cid,...data})});toast('Contract created!');closeModal();const cr=await api('/api/contracts');if(cr)contracts=await cr.json();renderContracts();}}]);});
async function signContract(id){await api(`/api/contracts/${id}/status`,{method:'PATCH',body:JSON.stringify({status:'signed'})});toast('Contract signed ✅');const cr=await api('/api/contracts');if(cr)contracts=await cr.json();renderContracts();}
async function deleteContract(id){if(!confirm('Delete contract?'))return;await api(`/api/contracts/${id}`,{method:'DELETE'});toast('Deleted');const cr=await api('/api/contracts');if(cr)contracts=await cr.json();renderContracts();}

// PROJECTS
function renderProjects(){
  document.getElementById('projectsGrid').innerHTML=projects.map(p=>`<div class="project-card" onclick="viewProject(${p.id})"><div class="project-name">${p.name}</div><div class="project-meta">${p.contact_name||'Internal'} · Due ${$d(p.due_date)}</div><div class="project-progress"><div class="project-progress-fill" style="width:${p.task_count?Math.round(p.done_count/p.task_count*100):0}%"></div></div><div class="project-stats"><span>${p.done_count||0}/${p.task_count||0} tasks</span><span class="status-badge" style="background:${p.status==='active'?'rgba(34,197,94,.12)':'rgba(59,130,246,.14)'};color:${p.status==='active'?'var(--accent-green)':'var(--accent-blue)'}">${p.status}</span></div></div>`).join('')||'<div style="color:var(--text-muted);font-size:13px">No projects yet</div>';
}
document.getElementById('addProjectBtn')?.addEventListener('click',()=>{const cOpts=contacts.map(c=>`<option value="${c.id}">${c.name} — ${c.company||'—'}</option>`).join('');openModal('New Project',`<div class="form-group"><label>Name</label><input class="fi" id="proj-name" placeholder="Project name"/></div><div class="form-group"><label>Contact (optional)</label><select class="fi" id="proj-contact"><option value="">None</option>${cOpts}</select></div><div class="form-group"><label>Description</label><textarea class="fi ta" id="proj-desc" rows="2"></textarea></div><div class="form-group"><label>Priority</label><select class="fi" id="proj-priority"><option value="high">High</option><option value="medium" selected>Medium</option><option value="low">Low</option></select></div><div class="form-group"><label>Due Date</label><input type="date" class="fi" id="proj-due"/></div>`,[{label:'Create Project',cls:'btn-primary',action:async()=>{const data={name:document.getElementById('proj-name').value.trim(),description:document.getElementById('proj-desc').value,priority:document.getElementById('proj-priority').value,due_date:document.getElementById('proj-due').value,contact_id:parseInt(document.getElementById('proj-contact').value)||null,status:'active'};if(!data.name){toast('Name required','warn');return}await api('/api/projects',{method:'POST',body:JSON.stringify(data)});toast('Project created!');closeModal();const pr=await api('/api/projects');if(pr)projects=await pr.json();renderProjects();}}]);});
async function viewProject(id){const res=await api(`/api/projects/${id}`);if(!res)return;const p=await res.json();openModal(p.name,`<div style="font-size:13px;color:var(--text-secondary);margin-bottom:14px">${p.description||'No description'}</div><div class="task-list">${(p.tasks||[]).map(t=>`<div class="task-item"><div class="task-check ${t.status==='done'?'done':''}" onclick="toggleTask(${t.id},'${t.status}',${id})">✓</div><div class="task-title ${t.status==='done'?'done':''}">${t.title}</div><span class="status-badge priority-${t.priority}" style="font-size:10px">${t.priority}</span><div class="task-due">${$d(t.due_date)}</div></div>`).join('')||'<p style="font-size:13px;color:var(--text-muted)">No tasks yet</p>'}</div>`,[{label:'+ Add Task',cls:'btn-ghost',action:()=>addTask(id)}]);}
async function toggleTask(tid,status,pid){const newStatus=status==='done'?'todo':'done';await api(`/api/tasks/${tid}`,{method:'PATCH',body:JSON.stringify({status:newStatus})});const pr=await api('/api/projects');if(pr)projects=await pr.json();renderProjects();viewProject(pid);}
async function addTask(pid){closeModal();openModal('Add Task',`<div class="form-group"><label>Title</label><input class="fi" id="task-title" placeholder="Task title"/></div><div class="form-group"><label>Priority</label><select class="fi" id="task-priority"><option value="high">High</option><option value="medium" selected>Medium</option><option value="low">Low</option></select></div><div class="form-group"><label>Due Date</label><input type="date" class="fi" id="task-due"/></div>`,[{label:'Add Task',cls:'btn-primary',action:async()=>{const data={title:document.getElementById('task-title').value.trim(),priority:document.getElementById('task-priority').value,due_date:document.getElementById('task-due').value,status:'todo'};if(!data.title){toast('Title required','warn');return}await api(`/api/projects/${pid}/tasks`,{method:'POST',body:JSON.stringify(data)});toast('Task added!');closeModal();const pr=await api('/api/projects');if(pr)projects=await pr.json();renderProjects();}}]);}

// HELP DESK
function renderHelpDesk(){
  const q=(document.getElementById('ticketSearch')?.value||'').toLowerCase();
  const st=document.getElementById('ticketFilterStatus')?.value||'';
  const pri=document.getElementById('ticketFilterPriority')?.value||'';
  const filtered=tickets.filter(t=>{const mq=!q||(t.ticket_number||'').toLowerCase().includes(q)||(t.subject||'').toLowerCase().includes(q);return mq&&(!st||t.status===st)&&(!pri||t.priority===pri)});
  document.getElementById('ticketBody').innerHTML=filtered.map(t=>`<tr><td style="font-weight:500">${t.ticket_number}</td><td>${t.subject}</td><td>${t.contact_name||'—'}</td><td><span class="status-badge priority-${t.priority}">${t.priority}</span></td><td><span class="status-badge tkt-${t.status}">${t.status.replace('_',' ')}</span></td><td style="color:var(--text-secondary)">${$ago(t.created_at)}</td><td><div class="actions-cell">${t.status!=='resolved'?`<button class="icon-btn" title="Resolve" onclick="resolveTicket(${t.id})"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><polyline points="2,8 6,12 14,4"/></svg></button>`:''}<button class="icon-btn" title="View" onclick="viewTicket(${t.id})"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M1 8s2.5-5 7-5 7 5 7 5-2.5 5-7 5-7-5-7-5z"/><circle cx="8" cy="8" r="2"/></svg></button></div></td></tr>`).join('')||'<tr><td colspan="7" style="padding:40px;text-align:center;color:var(--text-muted)">No tickets</td></tr>';
}
['ticketSearch','ticketFilterStatus','ticketFilterPriority'].forEach(id=>document.getElementById(id)?.addEventListener('input',renderHelpDesk));
['ticketFilterStatus','ticketFilterPriority'].forEach(id=>document.getElementById(id)?.addEventListener('change',renderHelpDesk));
document.getElementById('addTicketBtn')?.addEventListener('click',()=>{const cOpts=contacts.map(c=>`<option value="${c.id}">${c.name} — ${c.company||'—'}</option>`).join('');openModal('New Ticket',`<div class="form-group"><label>Contact</label><select class="fi" id="tkt-contact"><option value="">Select…</option>${cOpts}</select></div><div class="form-group"><label>Subject</label><input class="fi" id="tkt-subject" placeholder="Describe the issue…"/></div><div class="form-group"><label>Body</label><textarea class="fi ta" id="tkt-body" rows="3" placeholder="Full description…"></textarea></div><div class="form-group"><label>Priority</label><select class="fi" id="tkt-priority"><option value="high">High</option><option value="medium" selected>Medium</option><option value="low">Low</option></select></div>`,[{label:'Create Ticket',cls:'btn-primary',action:async()=>{const data={contact_id:parseInt(document.getElementById('tkt-contact').value)||null,subject:document.getElementById('tkt-subject').value.trim(),body:document.getElementById('tkt-body').value.trim(),priority:document.getElementById('tkt-priority').value};if(!data.subject||!data.body){toast('Subject and body required','warn');return}await api('/api/tickets',{method:'POST',body:JSON.stringify(data)});toast('Ticket created!');closeModal();const tr=await api('/api/tickets');if(tr)tickets=await tr.json();renderHelpDesk();}}]);});
async function resolveTicket(id){await api(`/api/tickets/${id}`,{method:'PATCH',body:JSON.stringify({status:'resolved'})});toast('Ticket resolved ✅');const tr=await api('/api/tickets');if(tr)tickets=await tr.json();renderHelpDesk();}
async function viewTicket(id){const res=await api(`/api/tickets/${id}`);if(!res)return;const t=await res.json();openModal(`${t.ticket_number} — ${t.subject}`,`<p style="font-size:13px;color:var(--text-secondary);margin-bottom:12px">${t.body}</p><div style="border-top:1px solid var(--border);padding-top:10px"><div style="font-size:11px;text-transform:uppercase;letter-spacing:.07em;color:var(--text-muted);margin-bottom:8px">Replies</div>${(t.messages||[]).map(m=>`<div style="padding:7px;background:var(--bg-elevated);border-radius:7px;margin-bottom:5px;font-size:13px">${m.content}</div>`).join('')||'<p style="font-size:13px;color:var(--text-muted)">No replies yet</p>'}<textarea class="fi ta" id="reply-text" rows="2" style="margin-top:8px" placeholder="Add a reply…"></textarea></div>`,[{label:'Send Reply',cls:'btn-primary',action:async()=>{const content=document.getElementById('reply-text').value.trim();if(!content)return;await api(`/api/tickets/${id}/messages`,{method:'POST',body:JSON.stringify({content})});toast('Reply sent');closeModal();}}]);}

// FINANCE
async function renderFinance(){
  const res=await api('/api/finance/summary');if(!res)return;const d=await res.json();
  document.getElementById('financeCards').innerHTML=`<div class="finance-card"><div class="fc-label">Total Revenue</div><div class="fc-value" style="color:var(--accent-green)">${$m(d.revenue)}</div><div class="fc-sub">From paid invoices</div></div><div class="finance-card"><div class="fc-label">Total Expenses</div><div class="fc-value" style="color:var(--accent-red)">${$m(d.expenses)}</div><div class="fc-sub">Approved expenses</div></div><div class="finance-card"><div class="fc-label">Net Profit</div><div class="fc-value" style="color:${d.profit>=0?'var(--accent-green)':'var(--accent-red)'}">${$m(d.profit)}</div><div class="fc-sub">Revenue minus expenses</div></div><div class="finance-card"><div class="fc-label">Pending Invoices</div><div class="fc-value" style="color:var(--accent-amber)">${$m(d.invoices_pending)}</div><div class="fc-sub">Awaiting payment</div></div>`;
  document.getElementById('expenseBody').innerHTML=expenses.map(e=>`<tr><td>${e.description}</td><td>${e.category}</td><td style="font-weight:500">${$m(e.amount)}</td><td style="color:var(--text-secondary)">${$d(e.date)}</td><td><span class="status-badge ${e.status==='approved'?'badge-Client':e.status==='pending'?'badge-Lead':'badge-Churned'}">${e.status}</span></td><td><div class="actions-cell">${e.status==='pending'&&CUSER.role==='admin'?`<button class="icon-btn" title="Approve" onclick="approveExpense(${e.id})"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><polyline points="2,8 6,12 14,4"/></svg></button>`:''}<button class="icon-btn del" onclick="deleteExpense(${e.id})"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M2 4h12M5 4V2h6v2M6 7v5M10 7v5M3 4l1 10h8l1-10"/></svg></button></div></td></tr>`).join('')||'<tr><td colspan="6" style="padding:40px;text-align:center;color:var(--text-muted)">No expenses</td></tr>';
}
document.getElementById('addExpenseBtn')?.addEventListener('click',()=>{openModal('Log Expense',`<div class="form-group"><label>Description</label><input class="fi" id="exp-desc" placeholder="What was this for?"/></div><div class="form-group"><label>Category</label><select class="fi" id="exp-cat"><option>Travel</option><option>Software</option><option>Marketing</option><option>Office</option><option>Meals</option><option>Equipment</option></select></div><div class="form-group"><label>Amount ($)</label><input type="number" class="fi" id="exp-amount" value="0"/></div><div class="form-group"><label>Date</label><input type="date" class="fi" id="exp-date"/></div>`,[{label:'Log Expense',cls:'btn-primary',action:async()=>{const data={description:document.getElementById('exp-desc').value.trim(),category:document.getElementById('exp-cat').value,amount:parseFloat(document.getElementById('exp-amount').value)||0,date:document.getElementById('exp-date').value,status:'pending'};if(!data.description){toast('Description required','warn');return}await api('/api/expenses',{method:'POST',body:JSON.stringify(data)});toast('Expense logged!');closeModal();const er=await api('/api/expenses');if(er)expenses=await er.json();renderFinance();}}]);});
async function approveExpense(id){await api(`/api/expenses/${id}/status`,{method:'PATCH',body:JSON.stringify({status:'approved'})});toast('Approved');const er=await api('/api/expenses');if(er)expenses=await er.json();renderFinance();}
async function deleteExpense(id){if(!confirm('Delete expense?'))return;await api(`/api/expenses/${id}`,{method:'DELETE'});toast('Deleted');const er=await api('/api/expenses');if(er)expenses=await er.json();renderFinance();}

// CAMPAIGNS
function renderCampaigns(){
  document.getElementById('campaignsList').innerHTML=campaigns.map(c=>`<div class="dash-panel" style="margin-bottom:10px"><div class="panel-header"><span class="panel-title">${c.name}</span><span class="status-badge ${c.status==='sent'?'badge-Client':'badge-Lead'}">${c.status}</span></div><div style="padding:14px 16px"><div style="font-size:13px;color:var(--text-secondary);margin-bottom:10px">Subject: ${c.subject||'—'} · Segment: ${c.segment||'all'}</div><div style="display:flex;gap:18px"><div><div style="font-family:var(--font-serif);font-size:22px">${c.opens||0}</div><div style="font-size:11px;color:var(--text-muted);text-transform:uppercase;letter-spacing:.07em">Opens</div></div><div><div style="font-family:var(--font-serif);font-size:22px">${c.clicks||0}</div><div style="font-size:11px;color:var(--text-muted);text-transform:uppercase;letter-spacing:.07em">Clicks</div></div><div style="margin-left:auto;display:flex;gap:6px;align-items:center">${c.status==='draft'?`<button class="btn-primary" style="font-size:12px;padding:6px 12px" onclick="sendCampaign(${c.id})">Send Campaign</button>`:''}<button class="btn-ghost" style="font-size:12px;padding:6px 10px" onclick="deleteCampaign(${c.id})">Delete</button></div></div></div></div>`).join('')||'<div style="padding:30px;color:var(--text-muted);font-size:13px">No campaigns yet</div>';
}
document.getElementById('addCampaignBtn')?.addEventListener('click',()=>{openModal('New Campaign',`<div class="form-group"><label>Campaign Name</label><input class="fi" id="camp-name" placeholder="e.g. May Newsletter"/></div><div class="form-group"><label>Subject</label><input class="fi" id="camp-subject" placeholder="Email subject line"/></div><div class="form-group"><label>Segment</label><select class="fi" id="camp-segment"><option value="all">All contacts</option><option value="leads">Leads only</option><option value="clients">Clients only</option><option value="partners">Partners only</option></select></div><div class="form-group"><label>Body (HTML or plain text)</label><textarea class="fi ta" id="camp-body" rows="5" placeholder="Hi {{name}},\n\nYour email content here…"></textarea></div>`,[{label:'Save Campaign',cls:'btn-primary',action:async()=>{const data={name:document.getElementById('camp-name').value.trim(),subject:document.getElementById('camp-subject').value.trim(),segment:document.getElementById('camp-segment').value,body:document.getElementById('camp-body').value};if(!data.name||!data.subject){toast('Name and subject required','warn');return}await api('/api/campaigns',{method:'POST',body:JSON.stringify(data)});toast('Campaign saved!');closeModal();const cr=await api('/api/campaigns');if(cr)campaigns=await cr.json();renderCampaigns();}}]);});
async function sendCampaign(id){if(!confirm('Send this campaign to all matching contacts?'))return;toast('Sending…','success');const res=await api(`/api/campaigns/${id}/send`,{method:'POST'});if(!res)return;const d=await res.json();toast(d.message||d.warning,d.warning?'warn':'success');const cr=await api('/api/campaigns');if(cr)campaigns=await cr.json();renderCampaigns();}
async function deleteCampaign(id){if(!confirm('Delete campaign?'))return;await api(`/api/campaigns/${id}`,{method:'DELETE'});toast('Deleted');const cr=await api('/api/campaigns');if(cr)campaigns=await cr.json();renderCampaigns();}

// AUTOMATION
function renderAutomation(){
  document.getElementById('flowBody').innerHTML=flows.map(f=>`<tr><td style="font-weight:500">${f.name}</td><td><span class="status-badge badge-Partner">${f.trigger}</span></td><td><span class="status-badge ${f.status==='active'?'badge-Client':'badge-Churned'}">${f.status}</span></td><td>${f.run_count||0} runs</td><td><div class="actions-cell"><button class="icon-btn" onclick="toggleFlow(${f.id},'${f.status}')"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M5 3l8 5-8 5z"/></svg></button><button class="icon-btn del" onclick="deleteFlow(${f.id})"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M2 4h12M5 4V2h6v2M6 7v5M10 7v5M3 4l1 10h8l1-10"/></svg></button></div></td></tr>`).join('')||'<tr><td colspan="5" style="padding:40px;text-align:center;color:var(--text-muted)">No automation flows</td></tr>';
}
document.getElementById('addFlowBtn')?.addEventListener('click',()=>{openModal('New Automation Flow',`<div class="form-group"><label>Flow Name</label><input class="fi" id="flow-name" placeholder="e.g. New Lead Welcome"/></div><div class="form-group"><label>Trigger</label><select class="fi" id="flow-trigger"><option value="contact_created">Contact Created</option><option value="no_contact_days">No Contact (days)</option><option value="stage_changed">Stage Changed</option></select></div><div class="form-group"><label>Action</label><select class="fi" id="flow-action"><option value="send_email">Send Email Template</option><option value="set_reminder">Set Follow-up Reminder</option></select></div><div class="form-group"><label>Template Name (for email action)</label><input class="fi" id="flow-template" placeholder="e.g. Introduction"/></div>`,[{label:'Create Flow',cls:'btn-primary',action:async()=>{const data={name:document.getElementById('flow-name').value.trim(),trigger:document.getElementById('flow-trigger').value,conditions:'[]',actions:JSON.stringify([{type:document.getElementById('flow-action').value,template:document.getElementById('flow-template').value}]),status:'active'};if(!data.name){toast('Name required','warn');return}await api('/api/automation',{method:'POST',body:JSON.stringify(data)});toast('Flow created!');closeModal();const fr=await api('/api/automation');if(fr)flows=await fr.json();renderAutomation();}}]);});
async function toggleFlow(id,status){const newStatus=status==='active'?'paused':'active';await api(`/api/automation/${id}`,{method:'PATCH',body:JSON.stringify({status:newStatus})});toast(`Flow ${newStatus}`);const fr=await api('/api/automation');if(fr)flows=await fr.json();renderAutomation();}
async function deleteFlow(id){if(!confirm('Delete flow?'))return;await api(`/api/automation/${id}`,{method:'DELETE'});toast('Deleted');const fr=await api('/api/automation');if(fr)flows=await fr.json();renderAutomation();}

// TEMPLATES
function renderTemplates(){
  const cColors={email:'var(--accent-blue)',whatsapp:'#25d366',sms:'var(--accent-amber)',note:'var(--accent-purple)'};
  document.getElementById('templatesGrid').innerHTML=templates.map(t=>`<div class="tpl-card"><div class="tpl-header"><span class="tpl-channel" style="background:${cColors[t.channel]||'var(--accent-blue)'}22;color:${cColors[t.channel]||'var(--accent-blue)'}">${t.channel}</span><span class="tpl-name">${t.name}</span></div>${t.subject?`<div style="font-size:11px;color:var(--text-secondary);padding:5px 13px 0;font-style:italic">${t.subject}</div>`:''}<div class="tpl-body">${t.body.slice(0,100)}${t.body.length>100?'…':''}</div><div class="tpl-footer"><button class="btn-ghost" style="font-size:12px;padding:5px 9px" onclick="editTemplate(${t.id})">Edit</button><button class="btn-ghost" style="font-size:12px;padding:5px 9px;color:var(--accent-red);border-color:rgba(239,68,68,.3)" onclick="deleteTemplate(${t.id})">Delete</button></div></div>`).join('')||'<div style="color:var(--text-muted);font-size:13px;padding:20px">No templates yet</div>';
}
document.getElementById('addTemplateBtn')?.addEventListener('click',()=>{openModal('New Template',`<div class="form-group"><label>Name</label><input class="fi" id="tpl-name" placeholder="Template name"/></div><div class="form-group"><label>Channel</label><select class="fi" id="tpl-channel"><option value="email">Email</option><option value="whatsapp">WhatsApp</option><option value="sms">SMS</option><option value="note">Note</option></select></div><div class="form-group"><label>Subject (email only)</label><input class="fi" id="tpl-subject" placeholder="Email subject with {{name}}"/></div><div class="form-group"><label>Body — use {{name}}, {{company}}, {{deal}}, {{sender_name}}</label><textarea class="fi ta" id="tpl-body" rows="5" placeholder="Hi {{name}},\n\n…"></textarea></div>`,[{label:'Save',cls:'btn-primary',action:async()=>{const data={name:document.getElementById('tpl-name').value.trim(),channel:document.getElementById('tpl-channel').value,subject:document.getElementById('tpl-subject').value.trim(),body:document.getElementById('tpl-body').value.trim()};if(!data.name||!data.body){toast('Name and body required','warn');return}await api('/api/templates',{method:'POST',body:JSON.stringify(data)});toast('Template saved!');closeModal();const tr=await api('/api/templates');if(tr)templates=await tr.json();renderTemplates();}}]);});
async function editTemplate(id){const t=templates.find(x=>x.id===id);if(!t)return;openModal('Edit Template',`<div class="form-group"><label>Name</label><input class="fi" id="tpl-name" value="${t.name}"/></div><div class="form-group"><label>Channel</label><select class="fi" id="tpl-channel"><option value="email" ${t.channel==='email'?'selected':''}>Email</option><option value="whatsapp" ${t.channel==='whatsapp'?'selected':''}>WhatsApp</option><option value="sms" ${t.channel==='sms'?'selected':''}>SMS</option><option value="note" ${t.channel==='note'?'selected':''}>Note</option></select></div><div class="form-group"><label>Subject</label><input class="fi" id="tpl-subject" value="${t.subject||''}"/></div><div class="form-group"><label>Body</label><textarea class="fi ta" id="tpl-body" rows="5">${t.body}</textarea></div>`,[{label:'Update',cls:'btn-primary',action:async()=>{const data={name:document.getElementById('tpl-name').value.trim(),channel:document.getElementById('tpl-channel').value,subject:document.getElementById('tpl-subject').value.trim(),body:document.getElementById('tpl-body').value.trim()};await api(`/api/templates/${id}`,{method:'PUT',body:JSON.stringify(data)});toast('Updated!');closeModal();const tr=await api('/api/templates');if(tr)templates=await tr.json();renderTemplates();}}]);}
async function deleteTemplate(id){if(!confirm('Delete?'))return;await api(`/api/templates/${id}`,{method:'DELETE'});toast('Deleted');const tr=await api('/api/templates');if(tr)templates=await tr.json();renderTemplates();}

// REMINDERS
function renderReminders(){
  document.getElementById('remindersBody').innerHTML=[...reminders].sort((a,b)=>new Date(a.due_at)-new Date(b.due_at)).map(r=>{const isPast=r.status==='pending'&&new Date(r.due_at)<new Date();return`<tr><td style="font-weight:500">${r.contact_name||'—'}</td><td><span class="status-badge badge-${r.channel}">${r.channel}</span></td><td style="font-size:12px;color:var(--text-secondary);max-width:200px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${r.message}</td><td style="color:${isPast?'var(--accent-red)':'var(--text-secondary)'}">${$d(r.due_at)}</td><td><span class="status-badge ${r.status==='done'?'badge-Client':isPast?'badge-Churned':'badge-Lead'}">${r.status==='done'?'done':isPast?'overdue':'pending'}</span></td><td><div class="actions-cell">${r.status!=='done'?`<button class="icon-btn" title="Done" onclick="doneReminder(${r.id})"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><polyline points="2,8 6,12 14,4"/></svg></button>`:''}<button class="icon-btn del" onclick="deleteReminder(${r.id})"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M2 4h12M5 4V2h6v2M6 7v5M10 7v5M3 4l1 10h8l1-10"/></svg></button></div></td></tr>`}).join('')||'<tr><td colspan="6" style="padding:40px;text-align:center;color:var(--text-muted)">No reminders set</td></tr>';
}
document.getElementById('addReminderBtn')?.addEventListener('click',()=>{const cOpts=contacts.map(c=>`<option value="${c.id}">${c.name} — ${c.company||'—'}</option>`).join('');openModal('Set Reminder',`<div class="form-group"><label>Contact</label><select class="fi" id="rem-contact"><option value="">Select…</option>${cOpts}</select></div><div class="form-group"><label>Channel</label><select class="fi" id="rem-channel"><option value="email">Email</option><option value="whatsapp">WhatsApp</option><option value="sms">SMS</option></select></div><div class="form-group"><label>Message</label><textarea class="fi ta" id="rem-msg" rows="3" placeholder="Hi {{name}}, just checking in…"></textarea></div><div class="form-group"><label>Send At</label><input type="datetime-local" class="fi" id="rem-due"/></div><div class="form-group"><label>Repeat every N days (optional)</label><input type="number" class="fi" id="rem-repeat" placeholder="e.g. 7"/></div>`,[{label:'Set Reminder',cls:'btn-primary',action:async()=>{const data={contact_id:parseInt(document.getElementById('rem-contact').value),channel:document.getElementById('rem-channel').value,message:document.getElementById('rem-msg').value.trim(),due_at:new Date(document.getElementById('rem-due').value).toISOString(),repeat_days:parseInt(document.getElementById('rem-repeat').value)||null};if(!data.contact_id||!data.message){toast('Contact and message required','warn');return}await api('/api/reminders',{method:'POST',body:JSON.stringify(data)});toast('Reminder set!');closeModal();const rr=await api('/api/reminders');if(rr)reminders=await rr.json();renderReminders();}}]);});
async function doneReminder(id){await api(`/api/reminders/${id}/done`,{method:'PATCH'});toast('Done!');const rr=await api('/api/reminders');if(rr)reminders=await rr.json();renderReminders();}
async function deleteReminder(id){if(!confirm('Delete?'))return;await api(`/api/reminders/${id}`,{method:'DELETE'});toast('Deleted');const rr=await api('/api/reminders');if(rr)reminders=await rr.json();renderReminders();}

// ANALYTICS
async function renderAnalytics(){
  const total=contacts.length||1;const statuses=['Lead','Client','Partner','Churned'];
  const sCols={Lead:'var(--accent-amber)',Client:'var(--accent-green)',Partner:'var(--accent-blue)',Churned:'var(--accent-red)'};
  const byCnt=Object.fromEntries(statuses.map(s=>[s,contacts.filter(c=>c.status===s).length]));
  const pipeline=contacts.reduce((s,c)=>s+(Number(c.deal)||0),0);
  const revenue=invoices.filter(i=>i.status==='paid').reduce((s,i)=>s+(Number(i.total)||0),0);
  const topDeals=[...contacts].filter(c=>c.deal>0).sort((a,b)=>b.deal-a.deal).slice(0,5);
  const fr=await api('/api/ai/forecast');const forecast=fr?await fr.json():null;
  document.getElementById('analyticsGrid').innerHTML=`
    <div class="analytics-panel"><div class="ap-title">Status Distribution</div>${statuses.map(s=>{const pct=Math.round(byCnt[s]/total*100);return`<div class="bar-row"><span class="bar-label">${s}</span><div class="bar-track" style="flex:1"><div class="bar-fill" style="width:${pct}%;background:${sCols[s]}"></div></div><span class="bar-val">${byCnt[s]}</span></div>`}).join('')}</div>
    <div class="analytics-panel"><div class="ap-title">Key Metrics</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px">${[{label:'Contacts',val:contacts.length},{label:'Pipeline',val:$m(pipeline)},{label:'Revenue',val:$m(revenue)},{label:'Proposals',val:proposals.length},{label:'Projects',val:projects.length},{label:'Open Tickets',val:tickets.filter(t=>t.status==='open').length}].map(m=>`<div style="background:var(--bg-elevated);border-radius:var(--radius-md);padding:10px 12px"><div style="font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:var(--text-muted);margin-bottom:4px">${m.label}</div><div style="font-family:var(--font-serif);font-size:20px">${m.val}</div></div>`).join('')}</div></div>
    <div class="analytics-panel"><div class="ap-title">Top Deals</div>${topDeals.map((c,i)=>`<div class="deal-row"><span class="deal-rank">${i+1}</span><div><div class="deal-name">${c.name}</div><div class="deal-company">${c.company||'—'}</div></div><div class="deal-amount">${$m(c.deal)}</div></div>`).join('')||'<p style="color:var(--text-muted);font-size:13px">No deals yet</p>'}</div>
    ${forecast?`<div class="analytics-panel"><div class="ap-title">Churn Risk</div>${(forecast.churn_risk||[]).slice(0,5).map(c=>`<div class="deal-row"><div><div class="deal-name">${c.name}</div><div class="deal-company">${c.days_since_contact}d since contact</div></div><span class="status-badge ${c.risk_level==='high'?'badge-Churned':c.risk_level==='medium'?'badge-Lead':'badge-Client'}">${c.risk_level}</span></div>`).join('')||'<p style="color:var(--accent-green);font-size:13px">No churn risk detected ✅</p>'}</div>`:''}`;
}

// TEAM
async function renderTeam(){const res=await api('/api/team');if(!res)return;const team=await res.json();document.getElementById('teamGrid').innerHTML=team.map((u,i)=>{const av=pal(u.user_name);return`<div class="team-card"><div class="team-card-header"><div style="width:38px;height:38px;border-radius:50%;background:${av.bg};color:${av.c};font-size:13px;font-weight:600;display:flex;align-items:center;justify-content:center">${init(u.user_name)}</div><div><div style="font-weight:500">${u.user_name}</div><div style="font-size:11px;color:var(--text-muted)">${u.role} · ${$ago(u.last_login)}</div></div>${i===0?'<span style="margin-left:auto;font-size:20px">🏆</span>':''}</div><div class="team-stats-grid"><div class="team-stat"><div class="ts-val">${u.contacts_added||0}</div><div class="ts-label">Contacts</div></div><div class="team-stat"><div class="ts-val">${u.messages_sent||0}</div><div class="ts-label">Messages</div></div><div class="team-stat"><div class="ts-val">${u.deals_closed||0}</div><div class="ts-label">Deals</div></div><div class="team-stat"><div class="ts-val" style="color:var(--accent-green)">${$m(u.revenue||0)}</div><div class="ts-label">Revenue</div></div></div></div>`}).join('')||'<div style="color:var(--text-muted);font-size:13px">No team data</div>';}

// BILLING
async function renderBilling(){const res=await api('/api/billing/plans');if(!res)return;const plans=await res.json();const current=TENANT.plan||'starter';document.getElementById('billingSubtitle').textContent=`Current: ${current} · ${TENANT.sub_status||'active'}`;document.getElementById('plansGrid').innerHTML=plans.map(p=>`<div class="plan-card ${p.id==='pro'?'popular':''}">${p.id==='pro'?'<div class="popular-tag">Most Popular</div>':''}<div class="plan-name">${p.name}</div><div class="plan-price">$${p.price}<span>/mo</span></div><ul class="plan-features">${p.features.map(f=>`<li>${f}</li>`).join('')}</ul><button class="plan-btn ${p.id===current?'current':p.id==='pro'?'primary':''}" onclick="selectPlan('${p.id}')" ${p.id===current?'disabled':''}>${p.id===current?'✓ Current Plan':`Upgrade to ${p.name}`}</button></div>`).join('');const wr=await api('/api/webhooks');const webhooks=wr?await wr.json():[];document.getElementById('webhookList').innerHTML=webhooks.length?webhooks.map(w=>`<div class="webhook-row"><span class="webhook-events">${w.events}</span><span class="webhook-url">${w.url}</span><button class="icon-btn del" onclick="delWebhook(${w.id})"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><line x1="3" y1="3" x2="13" y2="13"/><line x1="13" y1="3" x2="3" y2="13"/></svg></button></div>`).join(''):'<div style="padding:16px 18px;font-size:13px;color:var(--text-muted)">No webhooks configured.</div>';}
function selectPlan(plan){openModal(`Upgrade to ${plan}`,`<p style="font-size:13px;color:var(--text-secondary);line-height:1.7">Set <code>STRIPE_SECRET_KEY</code> and Price IDs in your <code>.env</code> file to activate Stripe payments.</p>`,[{label:'Confirm',cls:'btn-primary',action:async()=>{const res=await api('/api/billing/checkout',{method:'POST',body:JSON.stringify({plan})});const d=res?await res.json():{};toast(d.error||'Configure Stripe in .env first','warn');closeModal();}}]);}
document.getElementById('stripePortalBtn')?.addEventListener('click',async()=>{const res=await api('/api/billing/portal');const d=res?await res.json():{};if(d.url)window.open(d.url,'_blank');else toast(d.error||'Stripe not configured','warn');});
document.getElementById('addWebhookBtn')?.addEventListener('click',()=>{const evts=['contact.created','contact.updated','contact.deleted','invoice.paid','invoice.sent','message.sent','proposal.accepted'];openModal('Add Zapier Webhook',`<div class="form-group"><label>Webhook URL</label><input class="fi" id="wh-url" placeholder="https://hooks.zapier.com/…"/></div><div class="form-group"><label>Events</label>${evts.map(e=>`<label style="display:flex;align-items:center;gap:7px;font-size:13px;margin-bottom:5px;color:var(--text-secondary)"><input type="checkbox" value="${e}" class="wh-ev"/> ${e}</label>`).join('')}</div>`,[{label:'Save',cls:'btn-primary',action:async()=>{const url=document.getElementById('wh-url').value.trim();const events=[...document.querySelectorAll('.wh-ev:checked')].map(e=>e.value);if(!url||!events.length){toast('URL and events required','warn');return}const res=await api('/api/webhooks',{method:'POST',body:JSON.stringify({url,events})});const d=res?await res.json():{};toast(`Webhook saved! Secret: ${d.secret}`);closeModal();renderBilling();}}]);});
async function delWebhook(id){await api(`/api/webhooks/${id}`,{method:'DELETE'});toast('Deleted');renderBilling();}

// ADMIN
async function renderAdmin(){if(CUSER.role!=='admin')return;const[ur,ir]=await Promise.all([api('/api/users'),api('/api/integrations')]);const users=ur?await ur.json():[];const integs=ir?await ir.json():[];const connected=new Set(integs.filter(i=>i.enabled).map(i=>i.type));document.getElementById('userBody').innerHTML=users.map(u=>`<tr><td style="font-weight:500">${u.name}</td><td style="color:var(--text-secondary)">${u.email}</td><td><span class="role-chip role-${u.role}">${u.role}</span></td><td style="color:var(--text-muted)">${$ago(u.last_login)}</td><td>${u.id!==CUSER.id?`<button class="icon-btn del" onclick="deleteUser(${u.id})"><svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M2 4h12M5 4V2h6v2M6 7v5M10 7v5M3 4l1 10h8l1-10"/></svg></button>`:'<span style="font-size:11px;color:var(--text-muted)">You</span>'}</td></tr>`).join('');const IMETA={google_calendar:{icon:'📅',name:'Google Calendar'},twilio:{icon:'📱',name:'Twilio SMS'},slack:{icon:'💬',name:'Slack'},zapier:{icon:'⚡',name:'Zapier'},stripe:{icon:'💳',name:'Stripe'}};document.getElementById('integrationList').innerHTML=Object.entries(IMETA).map(([type,m])=>`<div class="integration-row"><div class="integ-icon">${m.icon}</div><div><div class="integ-name">${m.name}</div><div class="integ-status">${connected.has(type)?'Connected':'Not connected'}</div></div><div class="toggle-wrap"><label class="toggle"><input type="checkbox" ${connected.has(type)?'checked':''} onchange="toggleInteg('${type}',this.checked)"/><span class="toggle-slider"></span></label></div></div>`).join('');const br=await api('/api/branding');const branding=br?await br.json():{};const bf=document.getElementById('brandingForm');if(bf)bf.innerHTML=`<div class="form-group"><label>App Name</label><input class="fi" id="brand-name" value="${branding.app_name||'NexusCRM'}"/></div><div class="form-group"><label>Tagline</label><input class="fi" id="brand-tagline" value="${branding.tagline||''}"/></div><div class="form-group"><label>Primary Color</label><input type="color" class="fi" id="brand-color" value="${branding.primary_color||'#3b82f6'}" style="height:36px;padding:4px"/></div><button class="btn-primary" style="margin-top:4px" onclick="saveBranding()">Save Branding</button>`;const pi=document.getElementById('portalInviteWrap');if(pi){const cOpts=contacts.map(c=>`<option value="${c.id}">${c.name} — ${c.email||'no email'}</option>`).join('');pi.innerHTML=`<select class="fi" id="portalContact" style="margin-bottom:8px"><option value="">Select contact…</option>${cOpts}</select><button class="btn-ghost" onclick="sendPortalInvite()">Send Portal Invite</button>`;}}
document.getElementById('addUserBtn')?.addEventListener('click',()=>{openModal('Add Team Member',`<div class="form-group"><label>Full Name</label><input class="fi" id="nu-name" placeholder="Jane Smith"/></div><div class="form-group"><label>Email</label><input class="fi" id="nu-email" type="email" placeholder="jane@company.com"/></div><div class="form-group"><label>Password</label><input class="fi" id="nu-pass" type="password" placeholder="Min 6 characters"/></div><div class="form-group"><label>Role</label><select class="fi" id="nu-role"><option value="user">User</option><option value="admin">Admin</option></select></div>`,[{label:'Create User',cls:'btn-primary',action:async()=>{const data={name:document.getElementById('nu-name').value.trim(),email:document.getElementById('nu-email').value.trim(),password:document.getElementById('nu-pass').value,role:document.getElementById('nu-role').value};if(!data.name||!data.email||!data.password){toast('All fields required','warn');return}const res=await api('/api/auth/register',{method:'POST',body:JSON.stringify(data)});const d=res?await res.json():{};if(d.error){toast(d.error,'error');return}toast(`User ${data.name} created!`);closeModal();renderAdmin();}}]);});
async function deleteUser(id){if(!confirm('Delete user?'))return;await api(`/api/users/${id}`,{method:'DELETE'});toast('Deleted');renderAdmin();}
async function toggleInteg(type,enabled){await api(`/api/integrations/${type}/toggle`,{method:'PATCH',body:JSON.stringify({enabled})});toast(`${type} ${enabled?'enabled':'disabled'}`)}
async function saveBranding(){const data={app_name:document.getElementById('brand-name').value,tagline:document.getElementById('brand-tagline').value,primary_color:document.getElementById('brand-color').value};await api('/api/branding',{method:'PUT',body:JSON.stringify(data)});toast('Branding saved!');}
async function sendPortalInvite(){const cid=parseInt(document.getElementById('portalContact').value);if(!cid){toast('Select a contact','warn');return}const res=await api(`/api/portal/invite/${cid}`,{method:'POST'});if(!res)return;const d=await res.json();if(d.portalUrl){toast(d.message||'Invite sent!');openModal('Portal Link',`<p style="font-size:13px;color:var(--text-secondary);margin-bottom:10px">${d.message}</p><div style="background:var(--bg-elevated);border-radius:8px;padding:12px;font-size:12px;font-family:monospace;word-break:break-all;color:var(--accent-blue)">${d.portalUrl}</div>`,[])}else toast(d.error,'error');}

// SLIDE-OVER
function openPanel(){document.getElementById('overlay').classList.add('open');document.getElementById('slideover').classList.add('open')}
function closePanel(){document.getElementById('overlay').classList.remove('open');document.getElementById('slideover').classList.remove('open');editingId=null;isAdding=false;}
document.getElementById('overlay')?.addEventListener('click',closePanel);
document.getElementById('soClose')?.addEventListener('click',closePanel);
function setSOAv(name){setAv(document.getElementById('soAvatar'),name||'NC')}

function openView(id){
  const c=contacts.find(x=>x.id===id);if(!c)return;
  editingId=null;isAdding=false;setSOAv(c.name);
  document.getElementById('soName').textContent=c.name;
  document.getElementById('soRole').textContent=`${c.title||'—'} · ${c.company||'—'}`;
  const score=c.deal_score??0;
  document.getElementById('soBody').innerHTML=`<div style="display:flex;align-items:center;gap:8px;padding:8px 0;border-bottom:1px solid var(--border);margin-bottom:4px"><div style="flex:1;height:5px;background:var(--bg-elevated);border-radius:99px;overflow:hidden"><div style="width:${score}%;height:100%;background:${scoreColor(score)};border-radius:99px;transition:width .5s"></div></div><span style="font-size:12px;font-weight:600;color:${scoreColor(score)}">${score}%</span></div><div class="field-row"><span class="f-label">Email</span><span class="f-val" style="color:var(--accent-blue)">${c.email||'—'}</span></div><div class="field-row"><span class="f-label">Phone</span><span class="f-val">${c.phone||'—'}</span></div><div class="field-row"><span class="f-label">WhatsApp</span><span class="f-val">${c.whatsapp||c.phone||'—'}</span></div><div class="field-row"><span class="f-label">Company</span><span class="f-val">${c.company||'—'}</span></div><div class="field-row"><span class="f-label">Status</span><span class="f-val"><span class="status-badge badge-${c.status}">${c.status}</span></span></div><div class="field-row"><span class="f-label">Stage</span><span class="f-val">${c.stage||'—'}</span></div><div class="field-row"><span class="f-label">Deal</span><span class="f-val" style="font-weight:600;color:var(--accent-green)">${$m(c.deal)}</span></div><div class="field-row"><span class="f-label">Last Contact</span><span class="f-val">${$d(c.last_contact)}</span></div><div class="notes-section"><div class="notes-label">Notes</div><div class="notes-text">${c.notes||'No notes yet.'}</div></div>`;
  document.getElementById('soFooter').innerHTML=`<button class="btn-save" onclick="openEdit(${c.id})">Edit</button><button class="btn-ghost" style="color:#25d366;border-color:rgba(37,211,102,.3)" onclick="quickWA(${c.id})">WhatsApp</button><button class="btn-cancel" onclick="closePanel()">Close</button>`;
  openPanel();
}

function openEdit(id){const c=contacts.find(x=>x.id===id);if(!c)return;editingId=id;isAdding=false;setSOAv(c.name);document.getElementById('soName').textContent='Edit Contact';document.getElementById('soRole').textContent=c.company||'';renderForm(c);openPanel();}
function openAdd(){isAdding=true;editingId=null;setSOAv('NC');document.getElementById('soName').textContent='New Contact';document.getElementById('soRole').textContent='Fill in the details below';renderForm({name:'',email:'',phone:'',whatsapp:'',company:'',title:'',status:'Lead',stage:'Lead',deal:'',last_contact:'',notes:''});openPanel();}
function renderForm(c){
  const selStatus=['Lead','Client','Partner','Churned'].map(s=>`<option ${c.status===s?'selected':''}>${s}</option>`).join('');
  const selStage=['Lead','Qualified','Proposal','Closed'].map(s=>`<option ${(c.stage||'Lead')===s?'selected':''}>${s}</option>`).join('');
  document.getElementById('soBody').innerHTML=`<div class="field-row"><span class="f-label">Name</span><input class="fi" id="f-name" value="${c.name||''}" placeholder="Full name" oninput="liveAv()"/></div><div class="field-row"><span class="f-label">Email</span><input class="fi" id="f-email" type="email" value="${c.email||''}" placeholder="email@company.com"/></div><div class="field-row"><span class="f-label">Phone</span><input class="fi" id="f-phone" value="${c.phone||''}" placeholder="+1 000 000 0000"/></div><div class="field-row"><span class="f-label">WhatsApp</span><input class="fi" id="f-wa" value="${c.whatsapp||''}" placeholder="Same as phone?"/></div><div class="field-row"><span class="f-label">Company</span><input class="fi" id="f-company" value="${c.company||''}" placeholder="Company name"/></div><div class="field-row"><span class="f-label">Title</span><input class="fi" id="f-title" value="${c.title||''}" placeholder="Job title"/></div><div class="field-row"><span class="f-label">Status</span><select class="fi" id="f-status">${selStatus}</select></div><div class="field-row"><span class="f-label">Stage</span><select class="fi" id="f-stage">${selStage}</select></div><div class="field-row"><span class="f-label">Deal ($)</span><input class="fi" id="f-deal" type="number" value="${c.deal||''}" placeholder="0"/></div><div class="field-row"><span class="f-label">Last Contact</span><input class="fi" id="f-date" type="date" value="${c.last_contact||''}"/></div><div class="notes-section"><div class="notes-label">Notes</div><textarea class="fi ta" id="f-notes" placeholder="Notes…">${c.notes||''}</textarea></div>`;
  document.getElementById('soFooter').innerHTML=`<button class="btn-save" onclick="handleSave()">Save</button><button class="btn-cancel" onclick="${editingId?`openView(${editingId})`:'closePanel()'}">Cancel</button>`;
}
function liveAv(){const name=document.getElementById('f-name').value;setSOAv(name||'NC');document.getElementById('soName').textContent=name||'New Contact';}
async function handleSave(){
  const get=id=>document.getElementById(id)?.value||'';
  const data={name:get('f-name').trim(),email:get('f-email').trim(),phone:get('f-phone').trim(),whatsapp:get('f-wa').trim(),company:get('f-company').trim(),title:get('f-title').trim(),status:get('f-status'),stage:get('f-stage'),deal:parseFloat(get('f-deal'))||0,last_contact:get('f-date'),notes:get('f-notes').trim()};
  if(!data.name){toast('Name required','warn');return}
  let res;
  if(isAdding)res=await api('/api/contacts',{method:'POST',body:JSON.stringify(data)});
  else res=await api(`/api/contacts/${editingId}`,{method:'PUT',body:JSON.stringify(data)});
  if(!res?.ok){toast('Failed to save','error');return}
  const saved=await res.json();
  if(isAdding){contacts.push(saved)}else{const idx=contacts.findIndex(c=>c.id===saved.id);if(idx!==-1)contacts[idx]=saved;}
  document.getElementById('navContactCount').textContent=contacts.length;
  renderContacts();toast(`Contact ${isAdding?'created':'updated'}!`);
  if(isAdding)closePanel();else openView(editingId);
}
async function handleDelete(id){const c=contacts.find(x=>x.id===id);if(!c)return;if(!confirm(`Delete ${c.name}?`))return;await api(`/api/contacts/${id}`,{method:'DELETE'});contacts=contacts.filter(x=>x.id!==id);document.getElementById('navContactCount').textContent=contacts.length;closePanel();renderContacts();toast('Deleted');}

function exportCSV(){const hdrs=['Name','Email','Phone','WhatsApp','Company','Title','Status','Stage','Deal','Score','Last Contact','Notes'];const rows=contacts.map(c=>[c.name,c.email,c.phone,c.whatsapp,c.company,c.title,c.status,c.stage,c.deal,c.deal_score,c.last_contact,c.notes].map(v=>`"${(v||'').toString().replace(/"/g,'""')}"`).join(','));const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([[hdrs.join(','),...rows].join('\n')],{type:'text/csv'}));a.download='nexuscrm-contacts.csv';a.click();toast('Exported!');}

function openModal(title,bodyHtml,actions=[]){document.getElementById('modalTitle').textContent=title;document.getElementById('modalBody').innerHTML=bodyHtml;document.getElementById('modalFooter').innerHTML=[...actions.map(a=>`<button class="${a.cls||'btn-ghost'}" id="ma_${a.label.replace(/\s/g,'_')}">${a.label}</button>`),`<button class="btn-cancel" onclick="closeModal()">Cancel</button>`].join('');actions.forEach(a=>document.getElementById(`ma_${a.label.replace(/\s/g,'_')}`)?.addEventListener('click',a.action));document.getElementById('modalOverlay').style.display='flex';}
function closeModal(){document.getElementById('modalOverlay').style.display='none';invItems=[];propItems=[];}
document.getElementById('modalClose')?.addEventListener('click',closeModal);
document.getElementById('modalOverlay')?.addEventListener('click',e=>{if(e.target===e.currentTarget)closeModal();});

// BOOT
(async()=>{initSidebar();await loadAll();navigateTo('dashboard');})();
